### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Jack3G** [textadventures/quest#1030]
I dont know whats wrong it just says this     System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ThePix** [comment]
The 0x88982f50 error seems to be due to a bad file, and the text mentions a bitmap image, so I would guess that means you have a corrupted image file in the game.
If you are using the desktop version and creating your own game, I would move all images files out of the game folder (in fact any files except the game itself), and try to open it again. If it opens, then one of the files you moved is bad.
Move the files back one by one, and see if Quest can handle each one by trying to set it as the cover image on the Setup tab of the game object.

**Comment by ThePix** [comment]
I think this is resolved. The solution is also now in the docs.
