### ISSUE TITLE
KeyNotFoundException when creating a new game in Quest 5.8.0

### ISSUE THREAD

**Issue by apelisson57** [textadventures/quest#1042]
I just downloaded and installed Quest 5.8.0, and I received this error when trying to create a new game. I did not have this problem with Quest 5.7.x.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)

**Comment by HelpfulRandom** [comment]
Just manually uninstall quest, then install 5.8 again. I had the same problem and this seems to have fixed it. Your created games, etc should not be effected

**Comment by ThePix** [comment]
I think this has been resolved
