### ISSUE TITLE
Quest 5.8.0 editor failure to load correctly

### ISSUE THREAD

**Issue by Dravus** [textadventures/quest#1046]
Error codes presented at startup:
"System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

"System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()"

First error is repeated upon attempting to load any object within the Editor

**Comment by Nanospliccer** [comment]
I'm experiencing the same error here. Fresh installation on Windows 10, I open the editor for the first time, and I get this:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

When I close that, I get this:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

This seems like it'll be an ongoing problem with making anything in Quest 5.8.0.

**Comment by Animalibera1986** [comment]
i get this at startup, when the editor loads: 
System.MissingMethodException: Method not found: 'Void TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuSeparatorVisible(System.String, Boolean)'.
   at TextAdventures.Quest.Editor.SetTreeMenuVisibility()
   at TextAdventures.Quest.Editor.set_EditorStyle(EditorStyle value)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

**Comment by king-of-the-internet** [comment]
For what it's worth, I've had this same problem and fixed it by performing a clean reinstall.

**Comment by sgreig** [comment]
I'm also getting this error when I start Quest 5.8 on Windows 10.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.Redisplay()
   at TextAdventures.Quest.Main.ctlPlayer_Quit()
   at TextAdventures.Quest.Player._Lambda$__182-0()

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
