### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by NobleDave77** [textadventures/quest#1055]
I don't understand what it wants me to fix?
This is the error message:
System.Exception: Starting transaction when previous transaction not finished
   at TextAdventures.Quest.UndoLogger.StartTransaction(String command)
   at TextAdventures.Quest.EditorControls.DropDownTypesControl.Save()
   at TextAdventures.Quest.EditorControls.ElementEditor.Save()
   at TextAdventures.Quest.WPFElementEditor.SaveData()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlToolbar_HistoryClicked(String Key)
   at TextAdventures.Quest.MainToolbar.SetHistoryPosition(Int32 position, Boolean doRaiseEvent)
   at TextAdventures.Quest.MainToolbar.butBack_ButtonClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ThePix** [comment]
The error message comes from deep in Quest. It has got stuck doing one thing (one transaction). You have done something else, but it cannot do that because the earlier transaction is stuck. I think. This happened to me when I renamed an objected that was referenced elsewhere in a script. I had to restart Quest.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
