### ISSUE TITLE
Error ocurring

### ISSUE THREAD

**Issue by creepers0818** [textadventures/quest#1056]
i tried adding an printText in an If else statement

here is the error prompt
System.NullReferenceException: Object reference not set to an instance of an object.
   at TextAdventures.Quest.EditorControls.ScriptEditorControl.AddNewScriptCommand(String script)
   at TextAdventures.Quest.EditorControls.ScriptEditorControl.cmdAddScript_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs 

im new to this, so i dont know how to help of format it or whatever

**Comment by ThePix** [comment]
can you give any more details? Can you copy and paste the code into a comment (click the code view button in Quest).

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
