### ISSUE TITLE
Suddenly all of my text adventures are uneditable

### ISSUE THREAD

**Issue by LeadheadOnline** [textadventures/quest#1057]
I added a background art function to one file, opened photoshop to quickly edit a test picture and the game ran fine with the background image. I made a new one and when I tried to change the filename that the background art function pointed to, I got this error:

 System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88982F50
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

After closing and restarting, I couldn't edit any of my games anymore, even ones without the background art function, without getting the same error. However, if I make a new game the editor runs properly. 

It's worth noting that I don't have a GPU at the moment.

Thanks for all help, and the great software to begin with.

**Comment by LeadheadOnline** [comment]
So I ran my game again, background loaded fine as expected, and I looked at the debugger for a second before returning to the editor, expecting another error, and it just worked. I can't explain it.

**Comment by ThePix** [comment]
I am going to close this as it is fixed and we have no way now of knowing what the issue was.
