### ISSUE TITLE
What am I supposed to do here, I just updated Quest and this happened

### ISSUE THREAD

**Issue by JustAnotherRandomGuy** [textadventures/quest#1064]
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lpara)

What does this mean? What do I have to do to correct this? It does it every time I enter and pops up basically anytime I click on anything

**Comment by ThePix** [comment]
Sorry it took so long to reply!

Just seen another like this. The solution was to uninstall, restart the PC, and re-install Quest.
