### ISSUE TITLE
Error while playing gamebook

### ISSUE THREAD

**Issue by Imakunus** [textadventures/quest#1071]
I was trying to test my gamebook and received this error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at TextAdventures.Quest.PlayerHTML.ShowDevTools()
   at TextAdventures.Quest.Player.ctlToolbar_ButtonClicked(Object sender, ButtonClickedEventArgs args)
   at TextAdventures.Quest.Toolbar.HandleClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
More background:
This error only occured after trying to play the gamebook, and would not let me return to the editior unless I got out of the program and back in.
Before getting this error, I got this message: "Error launching game: could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

I haven't had this problem until today and I don't believe I changed anything significant. Is there a solution?

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
