### ISSUE TITLE
Error on opening

### ISSUE THREAD

**Issue by wooterslw** [textadventures/quest#1074]
I'm currently getting an error when I open my program I've been working on.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ThePix** [comment]
Can you start Quest at all, and create a new game? If not, uninstall, re-start the PC and re-install. Others have seen a similar error and that resolved it.

Otherwise it is an issue with your game file. The general approach to trouble-shooting is to back-up the game, and then to delete chunks from it until it loads okay. At the popint, you know the error was in the last chunk you deleted. You can then zero in on the issue. You have to delete in a way that does not introduce errors, so a knowledge of XML is vital. If you use Notepad++ to do it, you can set the file to XML format, then collapse nodes before deleting them to ensure you take out the whole node.

You could also try upload your game here.

**Comment by wooterslw** [comment]
Yeah. I finally found another post that said that. So I uninstalled it and re-installed and it fixed it. Thanks for the feedback!

**Comment by ThePix** [comment]
Thanks for letting us know. I have updated the "common problems" page so hopefully others will find it more easily.
