### ISSUE TITLE
Common issues with no common solution

### ISSUE THREAD

**Issue by frusterated13** [textadventures/quest#1082]
> System.Collections.Generic.KeyNotFoundException:` The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorController.GetElementTreeParent(Element o)
   at TextAdventures.Quest.EditorController.AddElementToTree(Element o, Nullable`1 position, String name)
   at TextAdventures.Quest.EditorController.AddElementAndChildrenToTree(Element o)
   at TextAdventures.Quest.EditorController.UpdateTree()
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

this error comes up everytime i try to launch the .aslx, no matter what i do in notepad++ no matter how many times i clean reinstall after restarting my computer. it always happens.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
