### ISSUE TITLE
System.ArgumentOutOfRangeException: Value must be non-negative and less than or equal to Int32.MaxValue.

### ISSUE THREAD

**Issue by kasperikoski** [textadventures/quest#1084]
When I try to start the editor, there comes an error saying:

```
System.ArgumentOutOfRangeException: Value must be non-negative and less than or equal to Int32.MaxValue.
Parameter name: pressure
   at System.GC.AddMemoryPressure(Int64 bytesAllocated)
   at System.Windows.Media.SafeMILHandle.UpdateEstimatedSize(Int64 estimatedSize)
   at System.Windows.Media.Imaging.BitmapFrameDecode.EnsureSource()
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I click OK and then comes:

```
Parameter name: pressure
   at System.GC.AddMemoryPressure(Int64 bytesAllocated)
   at System.Windows.Media.SafeMILHandle.UpdateEstimatedSize(Int64 estimatedSize)
   at System.Windows.Media.Imaging.BitmapFrameDecode.EnsureSource()
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()
```

Quest 5.8.0
Windows 10 Pro (1903)

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.

**Comment by Nowlielinuld** [comment]
Is this problem solved?

**Comment by alexwarren** [comment]
No, this was closed as I can't reproduce the problem. If you're experiencing the same thing, can you please add some details here so I can investigate.
