### ISSUE TITLE
method Exception

### ISSUE THREAD

**Issue by Llanerch** [textadventures/quest#1086]
System.MissingMethodException: Method not found: 'Void TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuSeparatorVisible(System.String, Boolean)'.
   at TextAdventures.Quest.Editor.SetTreeMenuVisibility()
   at TextAdventures.Quest.Editor.set_EditorStyle(EditorStyle value)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
