### ISSUE TITLE
Just updated - now can't edit

### ISSUE THREAD

**Issue by CheshireTiger** [textadventures/quest#1089]
I just updated a game i was working on ant it was working properly before, but after 5.8 update, it pops up this error whenever i click on room/object.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

NO IDEA WHAT THIS MEANS

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
