### ISSUE TITLE
(Broken link) 

### ISSUE THREAD

**Issue by Danario** [textadventures/quest#1091]
Pretty much, everytime i try to create a gamebook adventure i keep getting broken links... for no reason at all. How do i fix this problem? thanks 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetSelectedItem(String key)
   at TextAdventures.Quest.Editor.m_controller_RequestEdit(Object sender, RequestEditEventArgs e)
   at TextAdventures.Quest.EditorController.UIRequestEditElement(String key)
   at TextAdventures.Quest.EditorControls.WFGamebookOptions.m_manager_ExtraToolbarItemClicked(String action, String key)
   at TextAdventures.Quest.EditorControls.WFDictionaryEditorManager`1.DoAction(String action, String key)
   at TextAdventures.Quest.EditorControls.WFListEditor.ExtraItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
