### ISSUE TITLE
Starting a new Quest project.

### ISSUE THREAD

**Issue by DanielBogusz** [textadventures/quest#1094]
I get the following message:
System.MissingMethodException: Method not found: 'Void TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuSeparatorVisible(System.String, Boolean)'.
   at TextAdventures.Quest.Editor.SetTreeMenuVisibility()
   at TextAdventures.Quest.Editor.set_SimpleMode(Boolean value)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

The installation is new, and I just wanted to start a project with the dutch language selected.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
