### ISSUE TITLE
Error when opening quest 5.80

### ISSUE THREAD

**Issue by samaul741** [textadventures/quest#1125]
System.InvalidOperationException: Errore durante la creazione del form. Per informazioni dettagliate vedere Exception.InnerException. Errore: Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 Interfaccia non registrata. (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). ---> System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 Interfaccia non registrata. (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Speech.Internal.ObjectTokens.RegistryDataKey..ctor(String fullPath, IntPtr regHandle)
   at System.Speech.Internal.ObjectTokens.RegistryDataKey.Open(String registryPath, Boolean fCreateIfNotExist)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at TextAdventures.Quest.Player.set_UseSAPI(Boolean value)
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by alexwarren** [comment]
If this is still occurring, please:

- attach a game file which has the problem
- give the exact steps needed to reproduce it
- re-open this issue on GitHub
