### ISSUE TITLE
Quest Issues

### ISSUE THREAD

**Issue by IssyDrizzy** [textadventures/quest#1130]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TextAdventures.Quest.PlayerHTML.Reset()
   at TextAdventures.Quest.Player.ResetAfterGameFinished()
   at TextAdventures.Quest.Main.ctlPlayer_Quit()
   at TextAdventures.Quest.Player._Lambda$__182-0()

**Comment by alexwarren** [comment]
If this is still occurring, please:

- attach a game file which has the problem
- give the exact steps needed to reproduce it
- re-open this issue on GitHub
