### ISSUE TITLE
Error - Script Cannot be Edited or Removed

### ISSUE THREAD

**Issue by garbear17** [textadventures/quest#1131]
I'm making an escape room style game in Quest. There is a locked door, but if you have the key in your inventory, using the door takes you into another room. I made a small error in the script, but Quest will not allow me to change it and gives me a long error message instead.

There are 5 objects involved in this issue:
player (starting in room 1)
door (in room 1)
room 1
room 2
key (can be placed in player inventory)

This is the current script I am using. The part in italics was an error on my part. However, when I try to delete the error script, Quest sends me this error report and does not allow me to make any changes to any part of the script.

When "use door" is commanded:
1) If player does not have key, print message "door locked"
2) If player does have key then:
    a) The first time: print message "you turn the key until you hear a click.", after 2 seconds print message "you open the door, take one last look around and close the door behind you.", after 3 seconds move player to room 2.
    b) Otherwise: print message "you open the door, take one last look around and close the door behind you.", _move player to room 2_, after 3 seconds move player to room 2.

Obviously there's no need to move player twice. But when I try to delete the script in italics, Quest tells me this error message and does not remove it. I have also tried deleting the entire chain of scripts and it also gives me this error. So the script is kind of locked in to the project now.

Is there any solution? Thank you for reading!

System.Exception: Starting transaction when previous transaction not finished
   at TextAdventures.Quest.UndoLogger.StartTransaction(String command)
   at TextAdventures.Quest.EditableScripts.Remove(Int32[] indexes)
   at TextAdventures.Quest.EditorControls.ScriptEditorControl.ctlToolbar_Delete()
   at TextAdventures.Quest.EditorControls.ScriptToolbar.cmdDelete_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ThePix** [comment]
Take a look at this thread, it looks like a similar issue:
https://textadventures.co.uk/forum/quest/topic/sw-jzuaaw0mrih_i-wzfqq/solved-error-in-quest-after-trying-to-add-set-timeout-again

By the way, is this the on-line editor or stand-alone version?

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
