### ISSUE TITLE
Help with Quest issue

### ISSUE THREAD

**Issue by ericsson102** [textadventures/quest#1139]
hi, please can anyone help me with this:

 *****

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 Clase no registrada (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). ---> System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 Clase no registrada (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Speech.Internal.ObjectTokens.RegistryDataKey..ctor(String fullPath, IntPtr regHandle)
   at System.Speech.Internal.ObjectTokens.RegistryDataKey.Open(String registryPath, Boolean fCreateIfNotExist)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at TextAdventures.Quest.Player.set_UseSAPI(Boolean value)
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

*******

The program does not start and this message appears.

 Thank you very much for your attention and please forgive the inconvenience.

**Comment by NotEtto** [comment]
Actually, I think I've now solved this. There's a Windows security feature called Controlled Folder Access which stops software writing to your the folders you've selected, such as Documents, etc, to prevent rensomware attacks. If you want an app to access one of your controlled folders, you have to go into the security settings and let it through. Just go to settings, and in the search bar at th top, type in 'controlled folder access'. This will take you to the Ransomware Protection screen, and you'll see the option to 'Allow an app through controlled folder access'. It has worked for me.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
