### ISSUE TITLE
有没有大佬知道这种问题应该怎么解决

### ISSUE THREAD

**Issue by baisefox** [textadventures/quest#1163]
System.InvalidOperationException: 创建窗体时出错。有关详细信息，请参阅 Exception.InnerException。错误为: No voice installed on the system or none available with the current security setting. ---> System.PlatformNotSupportedException: No voice installed on the system or none available with the current security setting.
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at TextAdventures.Quest.Player.set_UseSAPI(Boolean value)
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by baisefox** [comment]
这个语音指的是什么？是不是因为安装位置不是c盘的原因（出厂自带的声卡软件应该都是在c盘吧），如果是，该怎么重新设定安装位置？现在重新启动安装程序都默认在上一次的安装位置

**Comment by alexwarren** [comment]
Duplicate of #1179
