### ISSUE TITLE
New error in the editor

### ISSUE THREAD

**Issue by Grumbleputty** [textadventures/quest#1165]
After adding a couple of very mundane objects to a game I've been working on, and suddenly whenever I open it in the editor I get the following two errors popping up whenever I click on an object or room on the left side of the screen (but not room exits), and the cursor becomes a spinning blue wheel. The main editor window remains blank unless I click on an exit

I've tried the following:

-  Saving under a new file name and restarting: no effect, the errors continue with the new project open in the editor
- Switching to code view: the error messages stop, but the blue wheel cursor appears when the cursor is at the top of the screen.
- Opening other projects: The errors stop
- Deleting the last few changes to I've made to the project: No effect

Still to try:

- shutting the computer down and restarting
- reinstalling the editor

Here are the two error messages, which tend to come one after the other:

System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

and the second one:

System.Runtime.InteropServices.COMException (0x88982F50): The component cannot be found. (Exception from HRESULT: 0x88982F50)

**Comment by Grumbleputty** [comment]
Just a further update, in case it helps anyone-

I created a new project, then went to the damaged project and copied the entire code over in code view. I pasted it into the new project and it ran without issue, although without any of the graphics I had used in my project.

I then went through and re-loaded all of the graphics individually, and the new project runs without issue.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
