### ISSUE TITLE
Verbs turn/switch on bug

### ISSUE THREAD

**Issue by MrArtV** [textadventures/quest#1178]
System.Exception: Starting transaction when previous transaction not finished
   at TextAdventures.Quest.UndoLogger.StartTransaction(String command)
   at TextAdventures.Quest.EditorControls.WFAttributesControl.cmdDelete_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
So to cut a long story short, I wanted to remove the turn on and turn off verb on an object, and it came down to the fact that the system didn't remove the verb. Instead of removing it, it adds script with different terms. see image.
![image](https://github.com/textadventures/quest/assets/157324762/d33f49da-8d62-4bbc-9655-954099608c6b)

**Comment by alexwarren** [comment]
If this is still occurring, please:

- attach a game file which has the problem
- give the exact steps needed to reproduce it
- re-open this issue on GitHub
