### ISSUE TITLE
"KeyNotFound" error loading game to edit

### ISSUE THREAD

**Issue by IainP** [textadventures/quest#778]
A pupil has been working on a game for the last couple of weeks with no problems. This week, she went to load her file and received the following error:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorController.GetElementTreeParent(Element o)
   at TextAdventures.Quest.EditorController.AddElementToTree(Element o, Nullable`1 position, String name)
   at TextAdventures.Quest.EditorController.AddElementAndChildrenToTree(Element o)
   at TextAdventures.Quest.EditorController.UpdateTree()
   at TextAdventures.Quest.Editor._Closure$__1._Lambda$__4()

We've not updated Quest or anything since her last session. Currently on v5.5 (though I note 5.5.1 has just been released, we can't update all the machines due to internal IT policy...).

I'm assuming it's some corruption in her game file :(

**Comment by alexwarren** [comment]
Could you email me the .aslx file? alex@textadventures.co.uk

**Comment by IainP** [comment]
I can't find a way to attach the game file here - too large to copy/paste.

**Comment by IainP** [comment]
Alex, thanks - will do.
