### ISSUE TITLE
Upgraded to windows 10. Quest wont open at all

### ISSUE THREAD

**Issue by nutjitzu** [textadventures/quest#861]
Here is what pops up when I try to open quest. Please help ASAP!:

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at GameBrowser.RecentItems.LoadRecentList()
   at GameBrowser.RecentItems..ctor(String listName)
   at GameBrowser.PlayBrowser..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GameBrowser.Launcher.InitializeComponent()
   at GameBrowser.Launcher..ctor()
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by richardlalancette** [comment]
Actually, I am on windows 10 and installed quest which worked fine.

**Comment by DaemonUmbra** [comment]
Have you tried a clean re-install of Quest?

**Comment by alexwarren** [comment]
Closing this as no repro.
