### ISSUE TITLE
Error on changing default download location

### ISSUE THREAD

**Issue by richardbutte** [textadventures/quest#870]
Windows 10, 64-bit
Quest build 5.6.5783.24161

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Username\Documents\Quest Games\Downloaded Games'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at TextAdventures.Quest.OptionsDialog.cmdOK_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by alexwarren** [comment]
I can't reproduce this. Did you change the folder to something and then delete it?

**Comment by richardbutte** [comment]
Ah, figured out what was causing it.

Looks like the error occurs if the original/default location no longer exists - has nothing to do with the location I'm trying to change it _to_.

Thus, to reproduce: delete the default download folder created upon installation, then try to change the download location to anything else. If you change the location _before_ deleting the default/currently set one, it works fine.

**Comment by alexwarren** [comment]
@richardbutte I still can't reproduce this if I follow your instructions. The Options window works fine if the download location has been deleted, and if I go to download a file, the folder gets recreated.
