### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by karinchan999** [textadventures/quest#876]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at TextAdventures.Quest.Scripts.FirstTimeScript.GetParameter(Int32 index)
   at TextAdventures.Quest.Scripts.LazyLoadScript.GetParameter(Int32 index)
   at TextAdventures.Quest.EditableScript.GetParameter(String index)
   at TextAdventures.Quest.EditableScript.DisplayString(Int32 index, Object newValue)
   at TextAdventures.Quest.EditableScriptBase.DisplayString()
   at TextAdventures.Quest.EditableScripts.DisplayString(Int32 index, String newValue)
   at TextAdventures.Quest.EditableScripts.DisplayString()
   at TextAdventures.Quest.EditorControls.ScriptEditorControl.m_scripts_Updated(Object sender, EditableScriptsUpdatedEventArgs e)
   at TextAdventures.Quest.EditableScripts.script_Updated(Object sender, EditableScriptUpdatedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at TextAdventures.Quest.EditableScriptBase.RaiseUpdated(EditableScriptUpdatedEventArgs e)
   at TextAdventures.Quest.EditableScriptBase.RaiseUpdateForNestedScriptChange(EditableScriptsUpdatedEventArgs e)
   at TextAdventures.Quest.EditableScript.nestedScript_Updated(Object sender, EditableScriptsUpdatedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at TextAdventures.Quest.EditableScripts.script_Updated(Object sender, EditableScriptUpdatedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at TextAdventures.Quest.EditableScriptBase.ScriptUpdated(Object sender, ScriptUpdatedEventArgs e)
   at TextAdventures.Quest.Scripts.ScriptBase.NotifyUpdate(ScriptUpdatedEventArgs args)
   at TextAdventures.Quest.Scripts.ScriptBase.SetParameter(Int32 index, Object value)
   at TextAdventures.Quest.Scripts.LazyLoadScript.SetParameter(Int32 index, Object value)
   at TextAdventures.Quest.EditableScript.SetParameter(String index, Object value)
   at TextAdventures.Quest.ScriptCommandEditorData.SetAttribute(String attribute, Object value)
   at TextAdventures.Quest.EditorControls.ControlDataHelper`1.Save(T newValue)
   at TextAdventures.Quest.EditorControls.ExpressionControl.Save()
   at TextAdventures.Quest.EditorControls.ExpressionControl.SimpleEditor_LostFocus(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.TextBoxBase.OnLostFocus(RoutedEventArgs e)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

It keeps showing up while I edit. Can anyone please help? I'm new here and I've been studying quest for two days now. Thank you.

**Comment by alexwarren** [comment]
Can you attach your game file plus some steps to reproduce the problem?

**Comment by karinchan999** [comment]
I'll use dropbox to send it, it says when I upload that it's not a supported file type.
https://www.dropbox.com/s/ul405nmf594muga/Half%20Life.aslx?dl=0

I was studying how the "If" thing works when it happened. It was at the "Modified Phone", the part where I wanted to add a "text to". At first I ignored it but it showed up again when I was editing the next part, which is the "switch on/off" part. I was editing the description when it's "switched on/off" and added the "First time..." in the script.

I think I'm confusing you but I hope you got my point. I really want to learn how this works. Thank you again.

**Comment by Pertex** [comment]
The problem ist the '#' within the firsttime function. 

        firsttime {
           msg ("#18")
        }

**Comment by karinchan999** [comment]
Then what should i do?

**Comment by Pertex** [comment]
You can wait for a patch or change your msg text something like 
 msg ("Actor no.18, Jade Cooper...

**Comment by karinchan999** [comment]
Oh alright. Thanks Pertex!
