### ISSUE TITLE
why wont quest open??

### ISSUE THREAD

**Issue by assassin604** [textadventures/quest#885]
Why wont my desktop part of Quest open
plz tell me what to do??
and what dose all this mean:

sorry an error has occourred in quest:

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at GameBrowser.RecentItems.LoadRecentList()
   at GameBrowser.RecentItems..ctor(String listName)
   at GameBrowser.PlayBrowser..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GameBrowser.Launcher.InitializeComponent()
   at GameBrowser.Launcher..ctor()
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()del()
plz tell me what to do??
System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at GameBrowser.RecentItems.LoadRecentList()
   at GameBrowser.RecentItems..ctor(String listName)
   at GameBrowser.PlayBrowser..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GameBrowser.Launcher.InitializeComponent()
   at GameBrowser.Launcher..ctor()
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()del()

**Comment by Pertex** [comment]
Here is Jay Nabonne's solution:
This appears to be a problem where a recent project ends up more than once in Quest's "recent" list in the registry. When it goes to build the recent list internally, it throws because more than one entry with the same filename exist. Looking at the code, I can't figure out (yet) how it gets into that state, but if you're willing to use "regedit", we can fix it.

Follow these steps:

    Run "regedit" (e.g. press the Windows key and then hit "R" and then type "regedit" in the box that pops up.) If it asks to be able to make changes to the system, say "yes".
    Under Computer in the tree on the left, look for HKEY_CURRENT_USER and open that folder.
    Look for SOFTWARE under that and open the folder.
    Search down for Quest under that and open the folder.

As this is the PlayBrowser, the key you care about is the one named "Recent". (If it were the EditBrowser one in the callback, you would have to focus on the EditorRecent key.)

The simplest way to fix this is to simply delete the Recent key (right-click on the word "Recent" and then choose "Delete" from the popup menu. Choose yes to confirm). Alternatively, you can open the Recent key (click on it) and look through the list of items for the ones beginning with "Recent", to see which entry is duplicated and remove only that one.

Note that if you do delete this key, then when you open Quest, the "recent" list on the Play tab will be empty until you begin playing games anew. I assume that is preferable to not being to open Quest at all!

**Comment by ThePix** [comment]
This just needs the solution needs to be in the documentation.
