### ISSUE TITLE
Not sure what I did?  If anyone has seen this error, I would love any help! Thanks

### ISSUE THREAD

**Issue by johntsangaris** [textadventures/quest#887]
System.Collections.Generic.KeyNotFoundException: Element not found: 'exit41' ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.Elements.Get(String key)
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.Elements.Get(String key)
   at TextAdventures.Quest.EditorVisibilityHelper.IsVisible(IEditorData data)
   at TextAdventures.Quest.EditorTab.IsTabVisible(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.UpdateControlVisibility()
   at TextAdventures.Quest.WPFElementEditor.set_SimpleMode(Boolean value)
   at TextAdventures.Quest.Editor.set_SimpleMode(Boolean value)
   at TextAdventures.Quest.Editor.ToggleSimpleMode()
   at TextAdventures.Quest.Controls.Menu.Menu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jaynabonne** [comment]
It looks like it's trying to set up an editor tab for something named "exit41". Did you at one point have an exit named that? (Quest may have named it that for you, so you may not know it had happened.) If you can look through the code view, you might be able to find it. Otherwise, if you could somehow get me the game file, I could take a look.

One question: it looks like this happens on a click. What are you doing when this occurs?

**Comment by ThePix** [comment]
If we hear no more on this, I am going to close it.

**Comment by ThePix** [comment]
Heard no more, so closing
