### ISSUE TITLE
The given key was not present in directory.

### ISSUE THREAD

**Issue by benjaminpants** [textadventures/quest#897]
I made a test walk through and then hit record and now my game is not working anymore!

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.WalkthroughRunner.get_Steps()
   at TextAdventures.Quest.Player.InitWalkthrough(String name)
   at TextAdventures.Quest.Main._Closure$__62-0._Lambda$__0()
   at TextAdventures.Quest.Player.BeginGame()
   at TextAdventures.Quest.Player._Lambda$__194-0()

**Comment by benjaminpants** [comment]
Restarting seems to have fixed it. But I am afraid once this game is really done and I really want to make a walk through the same issue will happen
