### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by tombricks** [textadventures/quest#899]
Running Windows Vista SP2 64-Bit 

-----------------------------------------------------------------------------------------------------------

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: dwrite.dll or wpftxt_v0400.dll ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x917a3fd6.CreateCModuleInitialize()
   at ?A0x917a3fd6.??__E?A0x917a3fd6@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by ThePix** [comment]
I am going to close this as I think it is an issue with the users game. This is better posted on the forum where it will get addressed rather more quickly!
