### ISSUE TITLE
Can't use Quest at all.

### ISSUE THREAD

**Issue by ghost** [textadventures/quest#919]
Every time I try to open Quest it says "Sorry, an error occured in Quest" and shows me this :

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'GameBrowser.PlayBrowser' that matches the specified binding constraints threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at GameBrowser.RecentItems.LoadRecentList()
   at GameBrowser.RecentItems..ctor(String listName)
   at GameBrowser.PlayBrowser..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GameBrowser.Launcher.InitializeComponent()
   at GameBrowser.Launcher..ctor()
   at TextAdventures.Quest.Main.InitializeComponent()
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Sorry it's pretty long :(

**Comment by ThePix** [comment]
This has been seen before. As a temporary fix, I have added a help page on what to do to get Quest working again, but I will leave this open as ideally we need to stp it happening at all.
http://docs.textadventures.co.uk/quest/problems.html

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
