### ISSUE TITLE
Quest 5.7.2 error. Unable to open the program after installation. 

### ISSUE THREAD

**Issue by BullRut** [textadventures/quest#939]
I just downloaded the Quest 5.7.2 desktop version and I am receiving this message when I try to open the application in a pop up window.

Quest.exe - Entry Point Not Found
The prochedure entry point nextafterf could not be located in the dynamix link library MSVCR120_CLR0400.dll.l

When I click ok I get the following error popup window with this error code.

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified procedure could not be found
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x98f606ec.CreateCModuleInitialize()
   at ?A0x98f606ec.??__E?A0x98f606ec@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.Main..ctor()
   --- End of inner exception stack trace ---
   at TextAdventures.Quest.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at TextAdventures.Quest.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

I have tried reinstalling after deleting the program, and I always end up with the same message.
I am running Windows 7 professional with service pack one. 

I would appreciate any help with this.

**Comment by thanosxxx** [comment]
I had a similar Error message in Windows 7. 

I upgraded to the latest .Net (4.7), and problem fixed. Is that the issue?

**Comment by ThePix** [comment]
No further response, so closing

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
