### ISSUE TITLE
Spell Checker in English, not needed in other languages.

### ISSUE THREAD

**Issue by thanosxxx** [textadventures/quest#960]
The new spellchecker in text boxes is on, even if the game is in another language than English.
It should check the game language before being enabled.

**Comment by KVonGit** [comment]
Sorry, that's my fault!

I've been trying to find a way to make it work for any language, but I'm having no luck.

I'm going to remove it completely.  I was about to submit a pull request anyway.

Just to save the link somewhere easily accessible, this is the page with all the info on SpellCheck:

https://msdn.microsoft.com/en-us/library/system.windows.controls.spellcheck(v=vs.110).aspx

**Comment by KVonGit** [comment]
I have submitted the pull request with code which totally disables SpellCheck.

Again, I am sorry about that!  I'm certain that it is quite frustrating!

**Comment by thanosxxx** [comment]
Hm... I'm getting the SpellChecker in Windows 10, but not in Windows 7. 
In Windows 7, I get an annoying Error popup, that says:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
   at TextAdventures.Quest.Editor.UpdateClipboardButtons()
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It is the case that the SpellChecker is the problem for it?

**Comment by KVonGit** [comment]
> In Windows 7, I get an annoying Error popup

>It is the case that the SpellChecker is the problem for it?

Maybe not.  I just built a version with no SpellCheck, and someone had the exact same errors popup when opening the editor.  I asked which Windows she is running, but she has not replied yet.  While I wait for that, I'm going to see if it works on my Windows 7 machine.  (I'll be back!)

**Comment by KVonGit** [comment]
Well...  It works fine on English language Windows 7.

...but someone else had an identical error, and they had the latest build with no SpellCheck.  So, I'm not sure that SpellCheck is the issue in Windows 7, but that's just a theory.
